### PR TITLE
Rebase against songkick

### PR DESCRIPTION
**Pull request by sgerrand**
:warning: WIP, please do not merge :warning: 

:information_desk_person: I've rebased against the master branch of `songkick/oauth-provider` and squashed @stuart-robinson's 3 commits into one (:hammer:).

Would be good to get some :eyes: on this: :wave: @mattsoutherden @lostie.

### CODE REVIEW

**Comment by sgerrand** [comment]
This shows the actual changes: https://github.com/songkick/oauth2-provider/compare/master...FundingCircle:upstream-master?expand=1

**Comment by lostie** [comment]
@sgerrand :raising_hand: It seems there's still a conflict between this branch and master :cry:

**Comment by sgerrand** [comment]
Testing the integration at https://github.com/fundingcircle/funding_circle_app/commits/songkickoauth2-provider :hourglass:

**Comment by sgerrand** [comment]
> It seems there's still a conflict between this branch and master

@lostie: I don't think I'll be able to get a clean merge in. I can try expanding @stuart-robinson's commits out again though, that might work. :runner:

**Comment by lostie** [comment]
LGTM :+1: 

> Testing the integration at https://github.com/fundingcircle/funding_circle_app/commits/songkickoauth2-provider :hourglass:

I was trying to do the same, but I'm stuck with `OpenSSL` issues :joy:

**Comment by sgerrand** [comment]
:no_good: integration tests [are failing](http://jenkins-master0.fcuat.co.uk/job/fca_non-prod/9174/changes), so still a WIP.

**Comment by lostie** [comment]
:cry:

**Comment by ecaselles** [comment]
@sgerrand I am not sure @stuart-robinson work was fully finished. Should we exclude it and keep this PR only as an update against the original repo? That way we can focus on fixing things broken due to changes in the gem itself.

**Comment by sgerrand** [comment]
@ecaselles: Apologies for the delayed response. Agreed.

**Comment by ecaselles** [comment]
@sgerrand :ok_hand:

**Comment by dalizard** [comment]
@sgerrand @ecaselles Does that mean we are going to try to use the non-forked version? :thought_balloon: :question:

**Comment by sgerrand** [comment]
> Does that mean we are going to try to use the non-forked version?

@dalizard: Unfortunately, there's a series of dependencies on the changes that @stuart-robinson made. If I get time, I'll spend a few days trying to get our various applications in a state where they can use the upstream version. For the moment I'll keep things as is. :smile_cat:

**Pull request closed without merging**
