### PR TITLE
Create refresh token on every sign in

### PR DESCRIPTION
**Pull request by 0mega**
This PR creates a refresh token every time the user authenticates. This should serve the refresh token on every sign in through API.

### CODE REVIEW

**Comment by HolixSF** [comment]
@sgerrand Do you know what other clients or services this change might potentially affect? I've spoken to the @FundingCircle/party-parrot team and they claim that Fund Reporting UK will need changes (they are also working on deprecating it).

**Comment by damien** [comment]
@HolixSF Relevant PRs @FundingCircle/party-parrot needs to complete before we can sunset Fund Reporting UK:

* FundingCircle/client-money-reporter#772
* FundingCircle/investor_intelligence#71

And I think that should be it. We'll let you know once we're in the clear 👍

**Comment by ecaselles** [comment]
@damien @HolixSF without knowing the details of how Fund Reporting UK works (does it use the Public API?), not sure how these changes could impact existing clients. In theory, we are just adding the possibility for clients to get their refresh tokens every time they sign in. That should be all. Therefore, clients can decide wether they want to use it or ignore it completely (and continue working as they do).

Having said that, I would suggest to deploy this into a UAT and QA that all our existing clients still function properly. We can help you with the app bit @HolixSF 😉

**Comment by sgerrand** [comment]
Seems the easiest path is to test for regression in an integrated environment with All The Things™.

**Comment by 0mega** [comment]
@damien IIRC the https://github.com/FundingCircle/client-money-reporter/ should not be affected by this. This is a **backwards compatible** change on authentication API level while the reports are made by using data from `reportdb-0{1,2}` which bypasses the API/application levels completely.

Therefore, I don't see any dependencies between this PR and the referenced PRs in the reporting projects. And again, even if there is any dependency on the API change proposed in this PR, it is backwards compatible.
Let me know if your concerns are not directly related to the mentioned reporting projects.

**Comment by coleby210** [comment]
@0mega / @ecaselles , Part of our discussion happened over slack, so sorry about that. `fund_reporting_uk` is an old app that we've almost completely replaced with `investor_intelligence`. The changes @damien has posted here are the last piece that `investor_intelligence` needs for us to completely remove the `fund_reporting_uk` app. You are correct @0mega that `client-money-reporter` does not rely on the API as that was our chosen path on replacing the insane amount of api calls that `fund_reporting_uk` does to build reports via the Funding Circle App API.

**Comment by 0mega** [comment]
Thanks for clarifying @coleby210. So is the problem in `fund_reporting_uk` because it heavily relies on the API? If yes, consider that this change is backwards compatible and does not alter any data that the client receive. The refresh token was being sent to the client together with the access_token but only the first time that client signs in. With this change, every time a client sings in he will always receive an `access_token` and a `refresh_token` which is not supposed to break a client unless the application is checking that no other fields can be received in the response, which is probably not the case.

Anyway, if more certainty is needed, as @ecaselles mentioned this can be tested on a UAT.
Just to clarify, I'm not trying to be pushy with this PR, just trying to explain what this PR is effectively changing. Ping me if I can help testing anything.

**Comment by coleby210** [comment]
@0mega Yeah the problem is `fund_reporting_uk` is 100% relying on the api. I think your changes should be fine, however we have very limited experience maintaining this app and it runs on rackspace... So if something goes wrong before our changes go out, we're pretty much screwed and will have a terrible time debugging and trying to fix this. I'm not even sure if `fund_reporting_uk` has a working (effective) UAT environment.

**Comment by sgerrand** [comment]
@coleby210: You just need to deploy a branch of `funding_circle_app` to UAT. You can run `fund_reporting_uk` against that.

**Pull request merged**
